
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lpjkfkvocnwdvxmjzrws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxwamtma3ZvY253ZHZ4bWp6cndzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0ODQxMjQsImV4cCI6MjA2NjA2MDEyNH0.hHUEsZgHpvAqU58vTWBl187w1hdhJSyqcLvRxsq-aG8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Export isSupabaseConfigured to indicate if Supabase is properly configured
export const isSupabaseConfigured = !!(SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY);
